[package]
name = "dissync-kalman-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "dissync_kalman_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.25.0"
dissync-kalman = {path = "../dissync-kalman"}
