name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cargo test
      run: cargo test --workspace --verbose
    - name: clippy
      run: cargo clippy --workspace -- -D warnings
    - name: cargo fmt
      run: cargo fmt --all --check
    - name: python test
      run: |
           python3 -m venv .venv
           . .venv/bin/activate
           pip install maturin
           maturin develop -m dissync-kalman-py/Cargo.toml
           python3 -c "import dissync_kalman_py; print(dissync_kalman_py)"
