name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: python setup
      run: ./run.sh setup-py
    - name: clippy and format
      run: ./run.sh style

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: rust test
      run: ./run.sh test-rs
    - name: python setup
      run: ./run.sh setup-py
    - name: python test
      run: ./run.sh test-py
